#!/usr/bin/env node

/**
 * Script to extract version from package.json and generate version.ts
 * This ensures the SDK version is always up-to-date and accessible programmatically.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Paths
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const versionTsPath = path.join(__dirname, '..', 'src', 'version.ts');

try {
    // Read package.json
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
    const version = packageJson.version;

    if (!version) {
        throw new Error('No version found in package.json');
    }

    console.log(`Extracting version: ${version}`);

    // Generate version.ts content
    const versionTsContent = `/**
 * Auto-generated file containing the current SDK version.
 * This file is generated by scripts/extract-version.js and should not be edited manually.
 */

/**
 * Current version of the enyo Energy App SDK.
 */
export const SDK_VERSION = '${version}';

/**
 * Gets the current SDK version.
 * @returns The semantic version string of the SDK
 */
export function getSdkVersion(): string {
    return SDK_VERSION;
}
`;

    // Write version.ts
    fs.writeFileSync(versionTsPath, versionTsContent, 'utf8');

    console.log(`✅ Generated version.ts with version ${version}`);

} catch (error) {
    console.error('❌ Error extracting version:', error.message);
    process.exit(1);
}