/**
 * Auto-generated file containing the current SDK version.
 * This file is generated by scripts/extract-version.js and should not be edited manually.
 */

/**
 * Current version of the enyo Energy App SDK.
 */
export const SDK_VERSION = '0.0.41';

/**
 * Gets the current SDK version.
 * @returns The semantic version string of the SDK
 */
export function getSdkVersion(): string {
    return SDK_VERSION;
}
